services:
  stl-db:
    image: postgres:15
    environment:
      POSTGRES_USER: stluser
      POSTGRES_PASSWORD: stlpass
      POSTGRES_DB: stldb
    ports:
      - "5432:5432"
    volumes:
      - stldb-data:/var/lib/postgresql/data

  stl-broker:
    image: apache/kafka:4.0.1
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@stl-broker:9093"
      KAFKA_PROCESS_ROLES: "broker,controller"
    ports:
      - "9092:9092"
      - "9093:9093" # controller port
    volumes:
      - kafka-data:/var/lib/kafka/data

  stl-core:
    image: stl-core:latest
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://stl-db:5432/stldb
      SPRING_DATASOURCE_USERNAME: stluser
      SPRING_DATASOURCE_PASSWORD: stlpass
      KAFKA_BOOTSTRAP_SERVERS: stl-broker:9092
    depends_on:
      - stl-db
      - stl-broker
    ports:
      - "8080:8080"

volumes:
  stldb-data:
  kafka-data:

